import { UserProfile } from '../types/auth';
import { ExamItem, RecentResult, ClassItem, AuditLogItem, AdminStats } from '../types/dashboard';

export const DEMO_PROFILES: Record<string, UserProfile> = {
  student: {
    id: 'demo-student-001',
    email: 'alex.chen@chem.edu',
    full_name: 'Alex Chen',
    role: 'student',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  teacher: {
    id: 'demo-teacher-001',
    email: 'dr.feynman@chem.edu',
    full_name: 'Dr. Evelyn Vance',
    role: 'teacher',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  admin: {
    id: 'demo-admin-001',
    email: 'admin@examfight.chem',
    full_name: 'Prof. Arthur Pendelton',
    role: 'admin',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
};

export const MOCK_STUDENT_ACTIVE_EXAMS: ExamItem[] = [
  {
    id: 'exam-act-001',
    title: 'Thermodynamics & Gibbs Free Energy Assessment',
    topic: 'Physical Chemistry',
    courseCode: 'CHEM-302',
    courseName: 'Physical Chemistry II',
    teacherName: 'Dr. Evelyn Vance',
    durationMinutes: 90,
    totalQuestions: 30,
    totalMarks: 100,
    passingMarks: 50,
    status: 'active',
    scheduledStart: new Date(Date.now() - 15 * 60000).toISOString(),
    scheduledEnd: new Date(Date.now() + 75 * 60000).toISOString(),
    proctoringActive: true,
  },
];

export const MOCK_STUDENT_UPCOMING_EXAMS: ExamItem[] = [
  {
    id: 'exam-up-001',
    title: 'Organic Reaction Mechanisms (Electrophilic Aromatic Substitution)',
    topic: 'Organic Chemistry',
    courseCode: 'CHEM-301',
    courseName: 'Advanced Organic Chemistry',
    teacherName: 'Dr. Evelyn Vance',
    durationMinutes: 120,
    totalQuestions: 40,
    totalMarks: 100,
    passingMarks: 45,
    status: 'scheduled',
    scheduledStart: new Date(Date.now() + 2 * 86400000).toISOString(),
    scheduledEnd: new Date(Date.now() + 2 * 86400000 + 7200000).toISOString(),
  },
  {
    id: 'exam-up-002',
    title: 'Coordination Complexes & Crystal Field Splitting Theory',
    topic: 'Inorganic Chemistry',
    courseCode: 'CHEM-201',
    courseName: 'Inorganic Chemistry Principles',
    teacherName: 'Dr. Marcus Holloway',
    durationMinutes: 60,
    totalQuestions: 25,
    totalMarks: 50,
    passingMarks: 25,
    status: 'scheduled',
    scheduledStart: new Date(Date.now() + 5 * 86400000).toISOString(),
    scheduledEnd: new Date(Date.now() + 5 * 86400000 + 3600000).toISOString(),
  },
];

export const MOCK_STUDENT_COMPLETED_EXAMS: ExamItem[] = [
  {
    id: 'exam-comp-001',
    title: 'Spectroscopy & Molecular Structure Identification (NMR & IR)',
    topic: 'Analytical Chemistry',
    courseCode: 'CHEM-405',
    courseName: 'Instrumental Analysis',
    teacherName: 'Dr. Evelyn Vance',
    durationMinutes: 90,
    totalQuestions: 35,
    totalMarks: 100,
    passingMarks: 40,
    status: 'completed',
    scheduledStart: new Date(Date.now() - 7 * 86400000).toISOString(),
    scheduledEnd: new Date(Date.now() - 7 * 86400000 + 5400000).toISOString(),
    studentScore: 92,
    studentGrade: 'A+',
  },
  {
    id: 'exam-comp-002',
    title: 'Chemical Kinetics & Arrhenius Activation Barrier Exam',
    topic: 'Physical Chemistry',
    courseCode: 'CHEM-302',
    courseName: 'Physical Chemistry II',
    teacherName: 'Dr. Evelyn Vance',
    durationMinutes: 60,
    totalQuestions: 20,
    totalMarks: 50,
    passingMarks: 20,
    status: 'completed',
    scheduledStart: new Date(Date.now() - 14 * 86400000).toISOString(),
    scheduledEnd: new Date(Date.now() - 14 * 86400000 + 3600000).toISOString(),
    studentScore: 44,
    studentGrade: 'A',
  },
];

export const MOCK_RECENT_RESULTS: RecentResult[] = [
  {
    id: 'res-001',
    examTitle: 'Spectroscopy & Molecular Structure Identification',
    topic: 'Analytical Chemistry',
    score: 92,
    totalMarks: 100,
    percentage: 92,
    grade: 'A+',
    completedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    rank: 'Top 3% (2/64)',
    status: 'passed',
  },
  {
    id: 'res-002',
    examTitle: 'Chemical Kinetics & Arrhenius Activation Barrier Exam',
    topic: 'Physical Chemistry',
    score: 44,
    totalMarks: 50,
    percentage: 88,
    grade: 'A',
    completedAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    rank: 'Top 10% (6/64)',
    status: 'passed',
  },
  {
    id: 'res-003',
    examTitle: 'Equilibrium Constant & Acid-Base Titration Curves',
    topic: 'General Chemistry',
    score: 85,
    totalMarks: 100,
    percentage: 85,
    grade: 'A-',
    completedAt: new Date(Date.now() - 25 * 86400000).toISOString(),
    rank: 'Top 15% (9/64)',
    status: 'passed',
  },
];

export const MOCK_TEACHER_CLASSES: ClassItem[] = [
  {
    id: 'class-001',
    name: 'CHEM-301: Advanced Organic Chemistry',
    code: 'ORG-301-F26',
    subject: 'Organic Chemistry',
    studentCount: 38,
    activeExamsCount: 1,
    createdAt: '2026-01-10',
    description: 'Reaction mechanisms, stereochemistry, retrosynthetic analysis, and organometallic catalytic cycles.',
  },
  {
    id: 'class-002',
    name: 'CHEM-302: Physical Chemistry & Kinetics',
    code: 'PHYS-302-F26',
    subject: 'Physical Chemistry',
    studentCount: 42,
    activeExamsCount: 2,
    createdAt: '2026-01-12',
    description: 'Thermodynamics, statistical mechanics, quantum states, and chemical reaction rates.',
  },
  {
    id: 'class-003',
    name: 'CHEM-405: Instrumental Chemistry & Spectroscopy',
    code: 'INST-405-F26',
    subject: 'Analytical Chemistry',
    studentCount: 24,
    activeExamsCount: 0,
    createdAt: '2026-01-15',
    description: 'NMR, FTIR, Mass Spectrometry, HPLC, and structural elucidations.',
  },
];

export const MOCK_TEACHER_EXAMS: ExamItem[] = [
  {
    id: 't-exam-001',
    title: 'Thermodynamics & Gibbs Free Energy Assessment',
    topic: 'Physical Chemistry',
    courseCode: 'CHEM-302',
    courseName: 'Physical Chemistry II',
    teacherName: 'Dr. Evelyn Vance',
    durationMinutes: 90,
    totalQuestions: 30,
    totalMarks: 100,
    passingMarks: 50,
    status: 'active',
    scheduledStart: new Date(Date.now() - 15 * 60000).toISOString(),
    scheduledEnd: new Date(Date.now() + 75 * 60000).toISOString(),
  },
  {
    id: 't-exam-002',
    title: 'Organic Reaction Mechanisms Midterm',
    topic: 'Organic Chemistry',
    courseCode: 'CHEM-301',
    courseName: 'Advanced Organic Chemistry',
    teacherName: 'Dr. Evelyn Vance',
    durationMinutes: 120,
    totalQuestions: 40,
    totalMarks: 100,
    passingMarks: 45,
    status: 'scheduled',
    scheduledStart: new Date(Date.now() + 2 * 86400000).toISOString(),
    scheduledEnd: new Date(Date.now() + 2 * 86400000 + 7200000).toISOString(),
  },
  {
    id: 't-exam-003',
    title: 'Spectroscopy & Molecular Structure Identification',
    topic: 'Analytical Chemistry',
    courseCode: 'CHEM-405',
    courseName: 'Instrumental Analysis',
    teacherName: 'Dr. Evelyn Vance',
    durationMinutes: 90,
    totalQuestions: 35,
    totalMarks: 100,
    passingMarks: 40,
    status: 'completed',
    scheduledStart: new Date(Date.now() - 7 * 86400000).toISOString(),
    scheduledEnd: new Date(Date.now() - 7 * 86400000 + 5400000).toISOString(),
  },
  {
    id: 't-exam-004',
    title: 'Quantum States & Schrodinger Wave Mechanics Draft',
    topic: 'Quantum Chemistry',
    courseCode: 'CHEM-302',
    courseName: 'Physical Chemistry II',
    teacherName: 'Dr. Evelyn Vance',
    durationMinutes: 60,
    totalQuestions: 20,
    totalMarks: 50,
    passingMarks: 25,
    status: 'draft',
    scheduledStart: new Date(Date.now() + 10 * 86400000).toISOString(),
    scheduledEnd: new Date(Date.now() + 10 * 86400000 + 3600000).toISOString(),
  },
];

export const MOCK_ADMIN_STATS: AdminStats = {
  totalStudents: 1420,
  totalTeachers: 68,
  totalExams: 342,
  activeUsers: 215,
  systemHealth: '99.98% Operational',
  activeSessions: 89,
};

export const MOCK_ADMIN_USERS: UserProfile[] = [
  {
    id: 'u-001',
    email: 'alex.chen@chem.edu',
    full_name: 'Alex Chen',
    role: 'student',
    created_at: '2026-01-15T08:30:00Z',
    updated_at: '2026-02-18T12:00:00Z',
  },
  {
    id: 'u-002',
    email: 'dr.feynman@chem.edu',
    full_name: 'Dr. Evelyn Vance',
    role: 'teacher',
    created_at: '2025-11-20T14:20:00Z',
    updated_at: '2026-02-20T09:45:00Z',
  },
  {
    id: 'u-003',
    email: 'admin@examfight.chem',
    full_name: 'Prof. Arthur Pendelton',
    role: 'admin',
    created_at: '2025-09-01T10:00:00Z',
    updated_at: '2026-02-21T18:00:00Z',
  },
  {
    id: 'u-004',
    email: 'sarah.lin@chem.edu',
    full_name: 'Sarah Lin',
    role: 'student',
    created_at: '2026-02-01T11:15:00Z',
    updated_at: '2026-02-19T16:30:00Z',
  },
  {
    id: 'u-005',
    email: 'm.holloway@chem.edu',
    full_name: 'Dr. Marcus Holloway',
    role: 'teacher',
    created_at: '2025-12-05T09:00:00Z',
    updated_at: '2026-02-14T11:20:00Z',
  },
  {
    id: 'u-006',
    email: 'priya.patel@chem.edu',
    full_name: 'Priya Patel',
    role: 'student',
    created_at: '2026-01-22T13:40:00Z',
    updated_at: '2026-02-21T08:15:00Z',
  },
];

export const MOCK_VERIFICATION_CODES = [
  {
    id: 'code-001',
    code: 'CHEM-FACULTY-2026-X9Y',
    issuedTo: 'Unassigned',
    isUsed: false,
    expiresAt: '2026-04-30',
    createdAt: '2026-02-10',
  },
  {
    id: 'code-002',
    code: 'CHEM-FACULTY-2026-R4T',
    issuedTo: 'Dr. Marcus Holloway (m.holloway@chem.edu)',
    isUsed: true,
    expiresAt: '2026-03-15',
    createdAt: '2026-01-05',
  },
  {
    id: 'code-003',
    code: 'CHEM-FACULTY-2026-K7M',
    issuedTo: 'Dr. Evelyn Vance (dr.feynman@chem.edu)',
    isUsed: true,
    expiresAt: '2026-03-30',
    createdAt: '2025-11-20',
  },
];

export const MOCK_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: 'log-001',
    timestamp: '2026-08-22 01:14:22',
    userEmail: 'alex.chen@chem.edu',
    userRole: 'student',
    action: 'Started Active Examination: Thermodynamics & Gibbs Free Energy',
    ipAddress: '192.168.1.104',
    status: 'success',
  },
  {
    id: 'log-002',
    timestamp: '2026-08-22 00:58:10',
    userEmail: 'dr.feynman@chem.edu',
    userRole: 'teacher',
    action: 'Published Exam: Organic Reaction Mechanisms Midterm',
    ipAddress: '10.0.4.12',
    status: 'success',
  },
  {
    id: 'log-003',
    timestamp: '2026-08-21 23:45:01',
    userEmail: 'unknown-intruder@test.com',
    userRole: 'anonymous',
    action: 'Blocked unauthorized privilege escalation attempt on /admin/dashboard',
    ipAddress: '185.220.101.5',
    status: 'warning',
  },
  {
    id: 'log-004',
    timestamp: '2026-08-21 22:30:19',
    userEmail: 'admin@examfight.chem',
    userRole: 'admin',
    action: 'Generated 3 new Teacher Verification Keys',
    ipAddress: '10.0.1.2',
    status: 'success',
  },
  {
    id: 'log-005',
    timestamp: '2026-08-21 21:12:00',
    userEmail: 'sarah.lin@chem.edu',
    userRole: 'student',
    action: 'Completed Exam: Spectroscopy & Molecular Structure Identification (Score: 94%)',
    ipAddress: '192.168.1.118',
    status: 'success',
  },
];
