import { ExamQuestion, ExamSubmissionResult } from '../types/exam';
import { StudentIntegrityReport } from '../types/proctoring';

export const MOCK_EXAM_QUESTIONS: Record<string, ExamQuestion[]> = {
  'exam-act-001': [
    {
      id: 'q-101',
      questionNumber: 1,
      type: 'mcq',
      domain: 'Physical Chemistry',
      topic: 'Thermodynamics & Gibbs Free Energy',
      difficulty: 'Intermediate',
      marks: 4,
      negativeMarks: 1,
      questionText: 'For the synthesis of ammonia by the Haber process at 500 K, determine the standard Gibbs Free Energy change ΔG° (in kJ/mol) given ΔH° = -92.4 kJ/mol and ΔS° = -198.2 J/(mol·K):',
      chemicalEquation: 'N₂(g) + 3H₂(g) ⇌ 2NH₃(g)',
      options: [
        { id: 'opt-1', label: 'A', text: 'ΔG° = +6.70 kJ/mol (Non-spontaneous at standard 500 K)', isCorrect: true },
        { id: 'opt-2', label: 'B', text: 'ΔG° = -191.5 kJ/mol (Spontaneous)', isCorrect: false },
        { id: 'opt-3', label: 'C', text: 'ΔG° = -6.70 kJ/mol', isCorrect: false },
        { id: 'opt-4', label: 'D', text: 'ΔG° = +191.5 kJ/mol', isCorrect: false },
      ],
      explanation: 'ΔG° = ΔH° - TΔS° = -92.4 kJ/mol - (500 K × -0.1982 kJ/(mol·K)) = -92.4 + 99.1 = +6.70 kJ/mol. Since ΔG° > 0 at 500 K, high temperatures thermodynamically disfavor ammonia synthesis despite accelerating reaction kinetics.',
      stepByStepRubric: [
        'Convert entropy units to kJ/(mol·K): -198.2 J/(mol·K) = -0.1982 kJ/(mol·K)',
        'Multiply T × ΔS°: 500 × (-0.1982) = -99.1 kJ/mol',
        'Apply Gibbs equation: -92.4 - (-99.1) = +6.70 kJ/mol',
      ],
    },
    {
      id: 'q-102',
      questionNumber: 2,
      type: 'numerical',
      domain: 'Physical Chemistry',
      topic: 'Equilibrium Constant & Electrochemistry',
      difficulty: 'Advanced',
      marks: 4,
      questionText: 'Calculate the standard cell potential E°_cell (in Volts) for a Daniel cell operating with standard Zinc and Copper half-cells at 298 K:',
      chemicalEquation: 'Zn(s) + Cu²⁺(aq) ⇌ Zn²⁺(aq) + Cu(s), where E°(Zn²⁺/Zn) = -0.76 V and E°(Cu²⁺/Cu) = +0.34 V',
      correctNumericalAnswer: 1.10,
      numericalTolerance: 0.02,
      numericalUnit: 'V',
      acceptableUnits: ['V', 'volts', 'volt'],
      explanation: 'E°_cell = E°_cathode (reduction) - E°_anode (oxidation) = +0.34 V - (-0.76 V) = +1.10 V. The positive cell potential confirms thermodynamic spontaneity under standard states.',
      stepByStepRubric: [
        'Identify cathode: Cu²⁺/Cu (higher reduction potential = +0.34 V)',
        'Identify anode: Zn²⁺/Zn (lower reduction potential = -0.76 V)',
        'Calculate E°_cell = 0.34 - (-0.76) = 1.10 V',
      ],
    },
    {
      id: 'q-103',
      questionNumber: 3,
      type: 'mcq',
      domain: 'Organic Chemistry',
      topic: 'Reaction Mechanisms (SN1 vs SN2)',
      difficulty: 'Intermediate',
      marks: 4,
      negativeMarks: 1,
      questionText: 'When (R)-2-bromobutane is treated with sodium cyanide (NaCN) in polar aprotic dimethylformamide (DMF) solvent, what is the stereochemical outcome of the major product?',
      chemicalEquation: '(R)-CH₃CH(Br)CH₂CH₃ + NaCN --[DMF]--> 2-methylbutanenitrile',
      options: [
        { id: 'opt-3a', label: 'A', text: '(S)-2-methylbutanenitrile via 100% Walden inversion (SN2 mechanism)', isCorrect: true },
        { id: 'opt-3b', label: 'B', text: 'Racemic mixture via planar carbocation intermediate (SN1 mechanism)', isCorrect: false },
        { id: 'opt-3c', label: 'C', text: 'Retention of configuration forming (R)-2-methylbutanenitrile', isCorrect: false },
        { id: 'opt-3d', label: 'D', text: 'E2 elimination forming predominantly but-2-ene', isCorrect: false },
      ],
      explanation: 'Secondary alkyl bromide with a strong, unhindered nucleophile (CN⁻) in a polar aprotic solvent (DMF) proceeds predominantly through a concerted bimolecular nucleophilic substitution (SN2) pathway, leading to complete backside attack and inversion of stereochemical configuration (Walden inversion).',
      stepByStepRubric: [
        'Substrate & Solvent diagnosis: Secondary halide in polar aprotic DMF favours SN2.',
        'Nucleophile strength: CN⁻ is a strong nucleophile.',
        'Stereochemical rule: SN2 backside attack results in complete configuration inversion (R → S).',
      ],
    },
    {
      id: 'q-104',
      questionNumber: 4,
      type: 'mcq',
      domain: 'Inorganic Chemistry',
      topic: 'Coordination Chemistry & Isomerism',
      difficulty: 'Advanced',
      marks: 4,
      negativeMarks: 1,
      questionText: 'Which of the following octahedral coordination complexes exhibits optical isomerism (exists as non-superimposable enantiomeric chiral pairs)?',
      chemicalEquation: 'Coordination Complexes of Cobalt and Platinum',
      options: [
        { id: 'opt-4a', label: 'A', text: 'cis-[Co(en)₂Cl₂]⁺ (where "en" is bidentate ethylenediamine)', isCorrect: true },
        { id: 'opt-4b', label: 'B', text: 'trans-[Co(en)₂Cl₂]⁺ possessing an inversion center', isCorrect: false },
        { id: 'opt-4c', label: 'C', text: '[Co(NH₃)₅Cl]²⁺ possessing C₄v symmetry', isCorrect: false },
        { id: 'opt-4d', label: 'D', text: 'trans-[Pt(NH₃)₂Cl₂] (Square planar)', isCorrect: false },
      ],
      explanation: 'cis-[Co(en)₂Cl₂]⁺ lacks an improper rotation axis (Sₙ), center of inversion (i), and plane of symmetry (σ), making the complex chiral and optically active. In contrast, the trans isomer has a plane of symmetry and inversion center, making it optically inactive (achiral).',
      stepByStepRubric: [
        'Identify chelate rings: Bidentate ethylenediamine ligands impose helical chirality in the cis geometry.',
        'Evaluate symmetry elements: trans isomer has σ and i symmetry; cis isomer lacks both.',
      ],
    },
    {
      id: 'q-105',
      questionNumber: 5,
      type: 'mechanism',
      domain: 'Organic Chemistry',
      topic: 'Electrophilic Addition & Carbocation Rearrangement',
      difficulty: 'Advanced',
      marks: 4,
      questionText: 'When 3,3-dimethylbut-1-ene reacts with hydrogen chloride (HCl), the predominant product obtained is 2-chloro-2,3-dimethylbutane rather than 3-chloro-3-methylbutane. Explain the chemical mechanism responsible for this product:',
      chemicalEquation: '(CH₃)₃C-CH=CH₂ + HCl → (CH₃)₂C(Cl)-CH(CH₃)₂ (Major Rearranged Product)',
      explanation: 'Step 1: Protonation of the alkene double bond follows Markovnikov’s rule to yield a secondary carbocation (CH₃)₃C-CH⁺-CH₃. Step 2: The secondary carbocation undergoes a 1,2-hydride or 1,2-methanide (methyl) shift. A 1,2-methyl shift creates a substantially more stable tertiary carbocation (CH₃)₂C⁺-CH(CH₃)₂. Step 3: Fast nucleophilic attack of chloride ion (Cl⁻) on the tertiary carbocation yields 2-chloro-2,3-dimethylbutane as the thermodynamic major product.',
      stepByStepRubric: [
        'Markovnikov protonation yielding 2° carbocation (+1.5 pts)',
        '1,2-Methyl shift to generate more stable 3° carbocation (+1.5 pts)',
        'Chloride capture forming tertiary chloroalkane (+1.0 pt)',
      ],
    },
  ],
};

export const MOCK_SAVED_SUBMISSIONS: Record<string, ExamSubmissionResult> = {
  'res-001': {
    id: 'res-001',
    examId: 'exam-comp-001',
    examTitle: 'Spectroscopy & Molecular Structure Identification (NMR & IR)',
    courseCode: 'CHEM-405',
    studentId: 'demo-student-001',
    studentName: 'Alex Chen',
    score: 92,
    totalMarks: 100,
    percentage: 92,
    grade: 'A+',
    passed: true,
    submittedAt: '2026-02-15T14:32:00Z',
    totalTimeSpentSeconds: 4860,
    questionsCorrect: 23,
    questionsIncorrect: 2,
    questionsUnattempted: 0,
    integrityScore: 98,
    proctoringFlagsCount: 0,
    domainBreakdown: [
      { domain: 'Analytical Chemistry', score: 38, total: 40, percentage: 95 },
      { domain: 'Organic Chemistry', score: 32, total: 35, percentage: 91.4 },
      { domain: 'Physical Chemistry', score: 22, total: 25, percentage: 88 },
    ],
    questionResults: [],
  },
};

export const MOCK_INTEGRITY_REPORTS: StudentIntegrityReport[] = [
  {
    studentId: 'demo-student-001',
    studentName: 'Alex Chen',
    studentEmail: 'alex.chen@chem.edu',
    examId: 'exam-act-001',
    examTitle: 'Thermodynamics & Gibbs Free Energy Assessment',
    submittedAt: '2026-08-22 01:14:22',
    integrityScore: 96,
    riskLevel: 'LOW',
    totalStrikes: 0,
    events: [
      { id: 'e1', timestamp: '2026-08-22 01:00:00', relativeTimeFormatted: '00:00:00', eventType: 'FULLSCREEN_ENTER', severity: 'info', description: 'Candidate entered locked fullscreen examination mode.' },
      { id: 'e2', timestamp: '2026-08-22 01:12:45', relativeTimeFormatted: '00:12:45', eventType: 'WINDOW_RESIZED', severity: 'info', description: 'Periodic table floating overlay opened.' },
    ],
  },
  {
    studentId: 'stu-992',
    studentName: 'Julian Thorne',
    studentEmail: 'j.thorne@chem.edu',
    examId: 'exam-act-001',
    examTitle: 'Thermodynamics & Gibbs Free Energy Assessment',
    submittedAt: '2026-08-21 23:45:10',
    integrityScore: 64,
    riskLevel: 'HIGH',
    totalStrikes: 2,
    events: [
      { id: 'e10', timestamp: '2026-08-21 23:10:02', relativeTimeFormatted: '00:10:02', eventType: 'FULLSCREEN_ENTER', severity: 'info', description: 'Candidate entered fullscreen examination environment.' },
      { id: 'e11', timestamp: '2026-08-21 23:18:20', relativeTimeFormatted: '00:18:20', eventType: 'TAB_SWITCH_BLUR', severity: 'warning', durationSeconds: 14, description: 'Browser tab lost focus (Candidate switched application window for 14 seconds).' },
      { id: 'e12', timestamp: '2026-08-21 23:18:34', relativeTimeFormatted: '00:18:34', eventType: 'TAB_SWITCH_FOCUS', severity: 'info', description: 'Focus regained after warning strike #1.' },
      { id: 'e13', timestamp: '2026-08-21 23:25:40', relativeTimeFormatted: '00:25:40', eventType: 'COPY_ATTEMPT', severity: 'warning', description: 'Blocked unauthorized text clipboard copy attempt on question #3.' },
      { id: 'e14', timestamp: '2026-08-21 23:32:15', relativeTimeFormatted: '00:32:15', eventType: 'FULLSCREEN_EXIT', severity: 'critical', durationSeconds: 8, description: 'Candidate exited fullscreen mode (Strike #2 issued).' },
    ],
  },
];
