// src/lib/teacherCodeService.ts
// Teacher Verification Code Management & Validation Service

export interface TeacherVerificationCode {
  id: string;
  code: string;
  issuedTo: string;
  isUsed: boolean;
  usedByEmail?: string;
  usedByName?: string;
  usedAt?: string;
  expiresAt: string;
  createdAt: string;
}

const STORAGE_KEY = 'exam_fight_teacher_codes_v2';

// Default initial authorization key generated by Admin
const DEFAULT_CODES: TeacherVerificationCode[] = [
  {
    id: 'code-admin-init-1',
    code: 'CHEM-FACULTY-2026-XP9R',
    issuedTo: 'Faculty Member Access Key',
    isUsed: false,
    expiresAt: '2026-12-31',
    createdAt: new Date().toISOString().split('T')[0],
  },
];

export const getStoredTeacherCodes = (): TeacherVerificationCode[] => {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(DEFAULT_CODES));
      return DEFAULT_CODES;
    }
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : DEFAULT_CODES;
  } catch (err) {
    console.error('Error reading teacher codes:', err);
    return DEFAULT_CODES;
  }
};

export const saveTeacherCodes = (codes: TeacherVerificationCode[]): void => {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(codes));
  } catch (err) {
    console.error('Error saving teacher codes:', err);
  }
};

export const generateTeacherCode = (
  issuedTo?: string,
  expiresDays: number = 180
): TeacherVerificationCode => {
  const codes = getStoredTeacherCodes();
  const suffix = Math.random().toString(36).substring(2, 6).toUpperCase();
  const code = `CHEM-FACULTY-2026-${suffix}`;

  const expDate = new Date();
  expDate.setDate(expDate.getDate() + expiresDays);

  const newCodeObj: TeacherVerificationCode = {
    id: `code-${Date.now()}-${Math.random().toString(36).substring(2, 6)}`,
    code,
    issuedTo: issuedTo?.trim() || 'Institutional Faculty Token',
    isUsed: false,
    expiresAt: expDate.toISOString().split('T')[0],
    createdAt: new Date().toISOString().split('T')[0],
  };

  const updated = [newCodeObj, ...codes];
  saveTeacherCodes(updated);
  return newCodeObj;
};

export const validateTeacherCode = (
  inputCode: string
): { isValid: boolean; error?: string; codeObj?: TeacherVerificationCode } => {
  if (!inputCode || !inputCode.trim()) {
    return {
      isValid: false,
      error: 'Teacher verification code is mandatory. Please enter a valid key issued by your administrator.',
    };
  }

  const cleanCode = inputCode.trim().toUpperCase();
  const codes = getStoredTeacherCodes();
  const found = codes.find((c) => c.code.toUpperCase() === cleanCode);

  if (!found) {
    return {
      isValid: false,
      error: `Invalid verification code "${cleanCode}". Please contact your administrator to receive an authorized faculty key.`,
    };
  }

  if (found.isUsed) {
    return {
      isValid: false,
      error: `This verification code has already been claimed by ${found.usedByEmail || 'another instructor'}. Each faculty key can only be used once.`,
    };
  }

  const now = new Date().toISOString().split('T')[0];
  if (found.expiresAt < now) {
    return {
      isValid: false,
      error: `This verification code expired on ${found.expiresAt}. Please request a new key from your administrator.`,
    };
  }

  return { isValid: true, codeObj: found };
};

export const claimTeacherCode = (
  inputCode: string,
  teacherEmail: string,
  teacherName: string
): boolean => {
  const cleanCode = inputCode.trim().toUpperCase();
  const codes = getStoredTeacherCodes();
  const index = codes.findIndex((c) => c.code.toUpperCase() === cleanCode);

  if (index < 0) return false;

  codes[index] = {
    ...codes[index],
    isUsed: true,
    usedByEmail: teacherEmail.trim(),
    usedByName: teacherName.trim(),
    usedAt: new Date().toISOString(),
  };

  saveTeacherCodes(codes);
  return true;
};

export const deleteTeacherCode = (codeId: string): boolean => {
  const codes = getStoredTeacherCodes();
  const filtered = codes.filter((c) => c.id !== codeId);
  if (filtered.length === codes.length) return false;
  saveTeacherCodes(filtered);
  return true;
};
